name: Build/release

on:
  push:
    branches: [main]

env:
  NODE_VERSION: '26.x'

permissions:
  contents: write

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - uses: actions/checkout@v7

      - name: Setup NodeJS
        uses: actions/setup-node@v7
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install dependencies
        run: npm ci

      - name: Build on Mac
        if: startsWith(matrix.os, 'macOS')
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npm run build:mac

      - name: Build on Linux
        if: startsWith(matrix.os, 'ubuntu')
        env:
          SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.SNAPCRAFT_STORE_CREDENTIALS }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npm run build:linux

      - name: Build on Windows
        if: startsWith(matrix.os, 'windows')
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npm run build:win

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v7
        with:
          name: electron-build-${{ matrix.os }}
          path: |
            dist/*

  release:
    runs-on: ubuntu-latest
    name: Release wpp
    if: github.ref == 'refs/heads/main'
    needs: build
    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: Setup NodeJS
        uses: actions/setup-node@v7
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Download All Artifacts
        uses: actions/download-artifact@v8
        with:
          pattern: electron-build-*
          path: all-dist/
          merge-multiple: true

      - name: Get version
        run: |
          echo "VERSION_TAG=v$(node -pe "require('./package.json').version")" >> $GITHUB_ENV

      - name: Check if version already exists in tags
        run: |
          echo "VERSION_HASH=$(git rev-parse -q --verify 'refs/tags/${{ env.VERSION_TAG }}')" >> $GITHUB_ENV
          echo "CHANGELOG_ANCHOR=$(echo $VERSION_TAG | sed -e 's/\.//g')" >> $GITHUB_ENV

      - name: Create Single Draft Release
        if: ${{ env.VERSION_HASH == '' }}
        id: create_draft
        uses: softprops/action-gh-release@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: ${{ env.VERSION_TAG }}
          name: ${{ env.VERSION_TAG }}
          draft: true
          prerelease: false
          files: |
            all-dist/**/*

      - name: Publish Release (if it does not exist)
        if: ${{ env.VERSION_HASH == '' }}
        uses: irongut/EditRelease@v1.2.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          id: ${{ steps.create_draft.outputs.id }}
          draft: false
          prerelease: false
